import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Luckiest_Guy } from "next/font/google"
import "./globals.css";
import Navbar from "@/components/NavBar";

/* const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
}); */
const luckiestGuy = Luckiest_Guy({
  weight: "400",
  subsets:['latin'],
  variable:"--font-luckiest-guy"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${luckiestGuy.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
